### ISSUE TITLE
TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by IsOverThere** [chemzqm/unite-location#7]
Anyone meet the below issue when run `Denite quickfix`?
```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/xxx/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/xxx/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 120, in _start
[denite]     self.gather_candidates()
[denite]   File "/home/xxx/.vim/bundle/denite.nvim/rplugin/python3/denite/ui/default.py", line 680, in gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "/home/xxx/.vim/bundle/denite.nvim/rplugin/python3/denite/denite.py", line 66, in gather_candidates
[denite]     source.context, source)
[denite]   File "/home/xxx/.vim/bundle/denite.nvim/rplugin/python3/denite/denite.py", line 75, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "/home/xxx/.vim/bundle/unite-location/rplugin/python3/denite/source/quickfix.py", line 56, in gather_candidates
[denite]     res.append(self.convert(item, context))
[denite]   File "/home/xxx/.vim/bundle/unite-location/rplugin/python3/denite/source/quickfix.py", line 40, in convert
[denite]     location='' if line == 0 and col == 0 else '%d col %d' % (line, col),
[denite] TypeError: %d format: a number is required, not str
[denite] Please execute :messages command.
Press ENTER or type command to continue
```

Vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 23 2018 11:56:58)
Python 3.5.2

**Comment by chemzqm** [comment]
Fixed in https://github.com/neoclide/denite-extra, use that plugin instead.
